### PR TITLE
macOS Big Sur

### PR DESCRIPTION
**Pull request by w0lfschild**
- Big Sur support    
- Xcode project changes
    - Restart the dock when bundle is built
    - Install bundle at `/Library/Application Support/MacEnhance/Plugins` when building
    - Bump version number to `1.8.0`

### CODE REVIEW

**Comment by dado3212** [comment]
Nice improvements.  Did you confirm that this doesn't break with non-Big Sur (if your only device is already updated I can locally test).

**Comment by w0lfschild** [comment]
I didn't do any tests on previous macOS but the existing changes only happen if the user is on Big Sur, so things should be exactly the same for Catalina and earlier,

**Comment by dado3212** [comment]
Will publish a new version probably Friday when I get a chance.

**Comment by oakif** [comment]
@w0lfschild Thanks a lot for this compatibility update, and thanks to dado for the app itself. Spaces Renamer is an invaluable tool for me as a student.

**Pull request merged**
